general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'a7163890trial'
      space: 'dev
      credentialsId: 'CF_CREDENTIALSID'
